name: OpenMinetopia
version: '1.4.0'
main: nl.openminetopia.OpenMinetopia
api-version: '1.21'
loader: nl.openminetopia.OpenMinetopiaLoader
authors: [ 'KaasPlakje', 'OmeJan', 'TheBathDuck', 'Swurfyy' ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: true
    Vault:
      required: false
    Skript:
      load: BEFORE
      required: false
    Citizens:
      load: BEFORE
      required: false
    FancyNpcs:
      load: BEFORE
      required: false
    LabyModServerAPI:
      load: BEFORE
      required: false
    TAB:
      load: AFTER
      required: false
    BetterTeams:
      load: BEFORE
      required: true
    DecentHolograms:
      load: BEFORE
      required: true